name = "Forge 1.20.1"
author = "Arthurmeade12"
version = "1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "131066517035da71cd4b9029b87d65f10abcad6c0aa3741e9172a51711110c1b"

[versions]
forge = "47.1.47"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
