name = "Forge 1.20.1"
author = "Arthurmeade12"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8af7bc9a14b550fd52c9158eb94261759c33eca2c2380c04954a40b9372ba8f"

[versions]
forge = "47.1.47"
minecraft = "1.20.1"
